name: Build and Deploy TravelBot backend To GCP CloudRun

on:
  push:
    branches: ["main"]
    paths:
      - 'backend/**'

env:
  PROJECT_ID: numeric-duality-276716
  DOCKER_REGION: northamerica-northeast2
  SERVICE_REGION: us-central1 # this is specific to the cloud run service
  GAR_LOCATION: northamerica-northeast2-docker.pkg.dev/numeric-duality-276716/travel-bot-gar/travel-bot
  SERVICE_NAME: travel-bot-backend

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_GAR_AUTH_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.DOCKER_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build backend --file backend/Dockerfile --tag ${{ env.GAR_LOCATION }}:latest
        working-directory: .

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}

  deploy:
    needs: build-push-artifact
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_CLOUD_RUN_AUTH_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: ${{ env.SERVICE_NAME }}
          region: '${{ env.SERVICE_REGION }}'
          image: '${{ env.GAR_LOCATION }}:latest' # we assumes last step already built a docker image